### PR TITLE
launch.py CLI updates

### PR DESCRIPTION
**Pull request by enmyj**
Update `launch.py` so that it can be used from the command line (useful when ensuring potential new images were built properly)

The first commit fixes ^^ but containers launched from the command line can't be killed using the webapp. It seems like this is because clicking "kill" from the webapp uses `ActivityLog` data to kill the container, but since the container is launched from the command line it won't have Activity Log data. Honestly not even sure this is worth fixing since nobody but me and Andrew use `launch.py` as a cli anyway and we can just use `docker kill <id>` 🤷‍♂

### CODE REVIEW

**Comment by semperstew** [comment]
In the interest of just getting something working quickly, I intermingled the function of the API and the ActivityLog when I was trying to protect user sessions. I have some time this weekend to work on this.

**Comment by semperstew** [comment]
Turns out I didn't intermingle the API and ActivityLog. What you want is to be able to kill a container from the webapp? We can probably give that ability to admins.

**Comment by semperstew** [comment]
@enmyj Commit 4d5fd71 fixes your issue. Admins can kill any container that is listed on the webapp, whether there is an ActivityLog entry on not. 🤙

**Comment by enmyj** [comment]
@semperstew and I both tested using a debug version of the webapp and launched a few containers from the CLI. Seems to be working.

**Pull request merged**
